# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'GlobalLogicList' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GlobalLogicList
  pod 'AFNetworking', '~> 3.0'
  pod 'Mantle', '~> 2.1'
  pod 'MBProgressHUD'

  target 'GlobalLogicListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GlobalLogicListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
